// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMvpAV-mMMT5JycDvm2itddZ3qIMyaWBI',
    appId: '1:77592297438:web:58b154625a8fd9af96a74f',
    messagingSenderId: '77592297438',
    projectId: 'flutter-training-session',
    authDomain: 'flutter-training-session.firebaseapp.com',
    databaseURL: 'https://flutter-training-session-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-training-session.firebasestorage.app',
    measurementId: 'G-G6V99RSZTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu1S5BBUIl5JvxCeZtbCxnB5aNSGqZ3R4',
    appId: '1:77592297438:android:2009259422e4cac596a74f',
    messagingSenderId: '77592297438',
    projectId: 'flutter-training-session',
    databaseURL: 'https://flutter-training-session-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-training-session.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiqpmDBVFgI-mH7KefS2UZn7zgS9I9YHg',
    appId: '1:77592297438:ios:dd88cc9aa6a82ac496a74f',
    messagingSenderId: '77592297438',
    projectId: 'flutter-training-session',
    databaseURL: 'https://flutter-training-session-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-training-session.firebasestorage.app',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiqpmDBVFgI-mH7KefS2UZn7zgS9I9YHg',
    appId: '1:77592297438:ios:dd88cc9aa6a82ac496a74f',
    messagingSenderId: '77592297438',
    projectId: 'flutter-training-session',
    databaseURL: 'https://flutter-training-session-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-training-session.firebasestorage.app',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMvpAV-mMMT5JycDvm2itddZ3qIMyaWBI',
    appId: '1:77592297438:web:39cbcee3a456075f96a74f',
    messagingSenderId: '77592297438',
    projectId: 'flutter-training-session',
    authDomain: 'flutter-training-session.firebaseapp.com',
    databaseURL: 'https://flutter-training-session-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-training-session.firebasestorage.app',
    measurementId: 'G-EYPST8B6BR',
  );

}